### ISSUE TITLE
learningperl6.com has content up that is horribly out of date; contact brian d foy

### ISSUE THREAD

**Issue by timo** [perl6/ye-olde#2]
The following is the first hit on google (after a dumb Ad) for "perl6 file handles":

http://www.learningperl6.com/Chapters/11.filehandles.html

This is Very Bad.

Can someone please contact Brian D. Foy about this? I've tried to reach out over twitter, but got no answer yet. Perhaps he isn't actively monitoring mentions or something?

**Comment by diakopter** [comment]
@briandfoy mention bump

**Comment by diakopter** [comment]
@timo perhaps explain explicitly why it is bad?

**Comment by zoffixznet** [comment]
I'd imagine because it's horribly out of date so anyone googling for the aforementioned topic will receive incorrect information :)

**Comment by timo** [comment]
here's a few examples:

```
$*ARGS    command line files
$*ARGVOUT    output for in place editing

my $fh = open $filename, $mode;
close $output;

my $append = open $destination, :a 
    err die "Could not append to $file: $!";

my $first_line = =$input;
my @array = =$input;
say $input.reverse.join('');

$line =~ s/\b([a-z])([a-z]+)([a-z])\b/$1 ~  ~ $2/

for $*ARGS {
    say "$*ARG: $_";
}

for =$=DATA {
    say if $_ % 2
}

for =$handle :prompt('$ ') { say $_ + 1 }

Curiously, the diamond operator is still around, but only as a sentimental stand-in for the old ARGV. We still read it by making it an iterator by adding the = to it:
for =<> { ... } 
```

All of these things i've pasted here are no longer valid.

**Comment by timo** [comment]
I don't know what other files are available in there. it's probably just a matter of googling with site:learningperl6.com. but i'm leaving the comp for multiple hours now, so won't check it myself.

**Comment by MadcapJake** [comment]
Check out the root page for learningperl6: http://www.learningperl6.com/
Everything should be redirecting there.

**Comment by briandfoy** [comment]
David Adler sent me an email and I'll take care of this. 

If you see other stuff from me that you think I need to update, just email me. Twitter is good for sending a message to the entire world, almost none of whom care about the message. Those things are easily lost in the noise. :)

**Comment by briandfoy** [comment]
Someone can close this issue.
